### ISSUE TITLE
Override image tap

### ISSUE THREAD

**Issue by dasmikko** [schibsted/tweet_ui#1]
Would it possible to have a way of overriding the image tap method? 

I have my own image viewer screen, it would like to use.

It would be even more awesome if when tapping on an image, I could get an list of all the tweet images, if there are multiple images. :)

**Comment by dasmikko** [comment]
#2 Made a pull request for this feature

**Comment by kawa89** [comment]
I've merged your code and made some fixes to it ;)
Please check https://github.com/schibsted/tweet_ui/commit/b886d7a7fd91c3187ca8d56639dacf50b5769b1a to check what I meant with `typdef`
