### ISSUE TITLE
type 'Null' is not a subtype of type 'double'

### ISSUE THREAD

**Issue by gadgetreviews** [schibsted/tweet_ui#103]
**Describe the bug**
When I try to read a tweet I get type 'Null' is not a subtype of type 'double' error

**To Reproduce**
```
    TwitterApi twitterApi = TwitterApi(
      client: TwitterClient(
        consumerKey: dotenv.env["twitterApiKey"]!,
        consumerSecret: dotenv.env["twitterApiKeySecret"]!,
        token: dotenv.env["twitterAccessToken"]!,
        secret: dotenv.env["twitterAccessTokenSecret"]!,
      ),
    );
    final tweet = await twitterApi.tweetService.show(id: "some id");
    json = tweet.toJson();
....
return TweetView.fromTweetV1(
      TweetV1Response.fromJson(json!),
    );
```
**Expected behavior**
I expected the tweet widget to be displayed

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Android emulator
 - OS: Android 10
 - Version: 4.0.1

**Additional context**
When I look at json comes from  dart_tweeter_api package, there was no id element. Instead there were only id_str element. Is that the root cause of the problem?

**Comment by wszeborowskimateusz** [comment]
This might be the problem. Could you send a whole json that you use to display the tweet?

**Comment by gadgetreviews** [comment]
> This should not be a problem as I see that id should not be required. Could you send a whole json that you use to display the tweet?

Thanks for quick reply. Would you please give me some advice how to get full json? Because when I try to print at android console, I can see the first 1000 characters. How can I get all of them? Thanks

**Comment by wszeborowskimateusz** [comment]
Maybe you could use a debugger and copy value from there?

**Comment by gadgetreviews** [comment]
This is what I can get with pretty json. I hope this will help.
```
I/flutter ( 4861): {
I/flutter ( 4861):   "created_at": "2022-04-16T19:02:24.000Z",
I/flutter ( 4861):   "id_str": "1515405264740134918",
I/flutter ( 4861):   "text": null,
I/flutter ( 4861):   "source": "<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>",
I/flutter ( 4861):   "truncated": false,
I/flutter ( 4861):   "in_reply_to_status_id_str": null,
I/flutter ( 4861):   "in_reply_to_user_id_str": null,
I/flutter ( 4861):   "in_reply_to_screen_name": null,
I/flutter ( 4861):   "user": {
I/flutter ( 4861):     "id_str": "44196397",
I/flutter ( 4861):     "name": "Elon Musk",
I/flutter ( 4861):     "screen_name": "elonmusk",
I/flutter ( 4861):     "location": "",
I/flutter ( 4861):     "derived": null,
I/flutter ( 4861):     "url": null,
I/flutter ( 4861):     "entities": {
I/flutter ( 4861):       "url": null,
I/flutter ( 4861):       "description": {
I/flutter ( 4861):         "urls": []
I/flutter ( 4861):       }
I/flutter ( 4861):     },
I/flutter ( 4861):     "description": "",
I/flutter ( 4861):     "protected": false,
I/flutter ( 4861):     "verified": true,
I/flutter ( 4861):     "status": null,
I/flutter ( 4861):     "followers_count": 82278915,
I/flutter ( 4861):     "friends_count": 114,
I/flutter ( 4861):     "listed_count": 90014,
I/flutter ( 4861):     "favorites_count": null,
I/flutter ( 4861):     "statuses_count": 17418,
I/flutter ( 4861):     "created_at": "2009-06-02T20:12:29.000Z",
I/flutter ( 4861):     "profile_banner_url": "https://pbs.twimg.com/profile_banners/44196397/1576183471",
I/flutter ( 4861):     "profile_image_url_https": "https://pbs.twimg.com/profile_images/15035914353245
```

**Comment by gadgetreviews** [comment]
Updated previous message. And it shows full json now.

**Comment by wszeborowskimateusz** [comment]
OK, I see a couple of problem with this tweet response:
- id is missing - previously I checked it wrongly - it is required
- created at has wrong format - according to the docs it should be
![Screenshot 2022-04-17 at 11 09 07](https://user-images.githubusercontent.com/31158740/163708080-190e5281-1432-45fb-99c0-7cc0525b89ef.png) 


Btw @kawa89 regarding first point - as I see we only use id to check if it is not less than 0 when displaying tweet link or user link. Do we need it? Cannot we use id_str?

**Comment by gadgetreviews** [comment]
So dart_tweeter_api package send incorrect json response?

**Comment by wszeborowskimateusz** [comment]
As I was looking at their code I found out they do some converts with the created_at field - I think they change the format of it.

Have a look at - https://github.com/robertodoering/twitter_api/blob/master/lib/src/utils/date_utils.dart


As I see in their tweet object they also don't fetch the **id** parameter.

**Comment by wszeborowskimateusz** [comment]
I think their package is more for getting and parsing tweet info into Dart objects. In our package we need original jsons.

**Comment by gadgetreviews** [comment]
So, what should I do?

**Comment by wszeborowskimateusz** [comment]
Maybe you could try calling twitter API directly not through the package?

**Comment by wszeborowskimateusz** [comment]
Or you might try to ask dart_twitter_api authors to add possibility to return raw json

**Comment by gadgetreviews** [comment]
I don't know how to authenticate. I tried with http with headers. But I don't know header format with authenticate for twitter api 1.1. There is no doc in twitter dev docs. it explains only curl, not http headers.

**Comment by wszeborowskimateusz** [comment]
Maybe you could have a look at this class? https://github.com/robertodoering/twitter_api/blob/master/lib/api/twitter_client.dart

**Comment by gadgetreviews** [comment]
I solved by using twitter_api package. So this is not a bug of twitter_ui package. Thanks for help.
