### ISSUE TITLE
Autoplay videos

### ISSUE THREAD

**Issue by jpcodr** [schibsted/tweet_ui#105]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
 A way to be able to play the videos automatically, through a configuration parameter, maybe `autoplayVideos: true|false`. Also, it'd be great if the video autoplays when visible on the screen. Something like [this](https://pub.dev/packages/inview_notifier_list)

**Comment by wszeborowskimateusz** [comment]
@jpcodr changes are deployed in version 4.0.2

**Comment by jpcodr** [comment]
@wszeborowskimateusz Thank you
