### ISSUE TITLE
Finding tweets that are not being rendered correctly

### ISSUE THREAD

**Issue by daver123** [schibsted/tweet_ui#14]
This tweet is not rendered correctly. I am seeing many others like this.

{
		"created_at": "Mon Jan 20 00:45:29 +0000 2020",
		"id": 1219058331102347264,
		"id_str": "1219058331102347264",
		"full_text": "so me &amp; 4 girls at work are taking a weekend trip to Chicago this June &amp; one of them today said \u201chold on ashlyn, I meant to ask you beforehand....are you gonna do anything to get the police called on us?\u201d \ud83d\ude02\ud83d\ude02\ud83d\ude02\ud83d\ude02\ud83d\ude02\ud83d\ude02",
		"truncated": false,
		"display_text_range": [0, 219],
		"entities": {
			"hashtags": [],
			"symbols": [],
			"user_mentions": [],
			"urls": []
		},
		"metadata": {
			"iso_language_code": "en",
			"result_type": "recent"
		},
		"source": "\u003ca href=\"http:\/\/twitter.com\/download\/iphone\" rel=\"nofollow\"\u003eTwitter for iPhone\u003c\/a\u003e",
		"in_reply_to_status_id": null,
		"in_reply_to_status_id_str": null,
		"in_reply_to_user_id": null,
		"in_reply_to_user_id_str": null,
		"in_reply_to_screen_name": null,
		"user": {
			"id": 46506347,
			"id_str": "46506347",
			"name": "ash",
			"screen_name": "ashlynluckett11",
			"location": "",
			"description": "University of Kentucky alumna",
			"url": "https:\/\/t.co\/fI37XghgnK",
			"entities": {
				"url": {
					"urls": [{
						"url": "https:\/\/t.co\/fI37XghgnK",
						"expanded_url": "http:\/\/www.ovinternational.org\/donate",
						"display_url": "ovinternational.org\/donate",
						"indices": [0, 23]
					}]
				},
				"description": {
					"urls": []
				}
			},
			"protected": false,
			"followers_count": 866,
			"friends_count": 368,
			"listed_count": 1,
			"created_at": "Thu Jun 11 22:13:51 +0000 2009",
			"favourites_count": 16649,
			"utc_offset": null,
			"time_zone": null,
			"geo_enabled": true,
			"verified": false,
			"statuses_count": 39968,
			"lang": null,
			"contributors_enabled": false,
			"is_translator": false,
			"is_translation_enabled": false,
			"profile_background_color": "C0DEED",
			"profile_background_image_url": "http:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png",
			"profile_background_image_url_https": "https:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png",
			"profile_background_tile": true,
			"profile_image_url": "http:\/\/pbs.twimg.com\/profile_images\/1214380088604733440\/F_2CxJA5_normal.jpg",
			"profile_image_url_https": "https:\/\/pbs.twimg.com\/profile_images\/1214380088604733440\/F_2CxJA5_normal.jpg",
			"profile_banner_url": "https:\/\/pbs.twimg.com\/profile_banners\/46506347\/1577842418",
			"profile_link_color": "0084B4",
			"profile_sidebar_border_color": "C0DEED",
			"profile_sidebar_fill_color": "DDEEF6",
			"profile_text_color": "333333",
			"profile_use_background_image": true,
			"has_extended_profile": false,
			"default_profile": false,
			"default_profile_image": false,
			"following": false,
			"follow_request_sent": false,
			"notifications": false,
			"translator_type": "none"
		},
		"geo": null,
		"coordinates": null,
		"place": null,
		"contributors": null,
		"is_quote_status": false,
		"retweet_count": 0,
		"favorite_count": 0,
		"favorited": false,
		"retweeted": false,
		"lang": "en"
	}

TWEET_UI renders it like this

![image](https://user-images.githubusercontent.com/59463749/72695798-dc984d00-3b07-11ea-8688-c12189243a8b.png)

TWITTER renders it like this
![image](https://user-images.githubusercontent.com/59463749/72695839-03ef1a00-3b08-11ea-81b5-165ef2396918.png)

**Comment by daver123** [comment]
Also you be nice to have time along with the date.

**Comment by kawa89** [comment]
Nice catch. Will try to fix it ASAP ;-)

**Comment by kawa89** [comment]
Fixed in version 1.1.0 :-) I also added time to the byline (for now only 24H format).

**Comment by daver123** [comment]
I made this change for 12hr time since I needed it.

![image](https://user-images.githubusercontent.com/59463749/73978447-5ac36480-48fa-11ea-82b2-7762a64b243f.png)

changed tweet_vm.dart

added a createdAtTime: _createdAtTime(tweet), to the tweetvm model

and the method 
   static String _createdAtTime(Tweet tweet) {
    DateFormat twitterFormat = new DateFormat("EEE MMM dd HH:mm:ss '+0000' yyyy");
    final dateTime = twitterFormat.parseUTC(tweet.createdAt).toLocal();
	
	DateFormat displayFormatTime = new DateFormat("h:mm a");
	return displayFormatTime.format(dateTime);
  }
  


and for byline.dart added a row for the date with time

	Row(
          mainAxisSize: MainAxisSize.max,
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: <Widget>[
            Expanded(
              child: Row(
                mainAxisSize: MainAxisSize.min,
                mainAxisAlignment: MainAxisAlignment.start,
                children: <Widget>[
				Text(
                      tweetVM.createdAt,
                      style: userScreenNameStyle,
                      textAlign: TextAlign.start,
                      softWrap: false,
                    ),
				Text(
                    " • " + tweetVM.createdAtTime,
                    style: userScreenNameStyle,
                    textAlign: TextAlign.start,
                  )]))])
				
				
		]);

**Comment by kawa89** [comment]
Nice. Will try to add some configuration for this in the next release ;-)

**Comment by daver123** [comment]
Oops I just realized even the Data displayed in your code is not correct for the users local timezone as well.

A tweet with created_at = "Sat Feb 22 04:39:00 +0000 2020" where my local timezone is -5h from this time. That means its 11:39PM on Sat Feb 21 my local time. Your code displays "Sat Feb 22"

Had to include the .toLocal() in your function to ensure the date is adjusted to my local date of the tweet. That way, when I click on the tweet and it jumps to twitter.com, the date matches with what twitter displays.

  static String _createdAt(Tweet tweet) {
    DateFormat twitterFormat = new DateFormat("EEE MMM dd HH:mm:ss '+0000' yyyy");
    DateFormat displayFormat = new DateFormat("MM.dd.yyyy");
    final dateTime = twitterFormat.parseUTC(tweet.createdAt).toLocal();	
    return displayFormat.format(dateTime);
  }

**Comment by kawa89** [comment]
👍 Will check it this week with a PR that is pending from another user ;)
