### ISSUE TITLE
Redesign widgets to look like the native embedded on website ones

### ISSUE THREAD

**Issue by ercadev** [schibsted/tweet_ui#19]
**Is your feature request related to a problem? Please describe.**
I want the tweets to look more natural. Showing a tweet should look like the result you get from the "embed a tweet on your website" (example picture in additional context)

**Describe the solution you'd like**
I could redesign the Widgets to look as close to the embedded version as possible

**Describe alternatives you've considered**
Add widgets like `TweetEmbedded()` to this package. Or I would fork this repo and rewrite all widgets and use it on my own, but if more than I want this feature adding widgets to this package would be beter.

**Additional context**
![Skärmavbild 2020-03-16 kl  16 44 19](https://user-images.githubusercontent.com/25930062/76775270-6598d100-67a5-11ea-82ba-2c389ecd66fe.png)

**Comment by kawa89** [comment]
Hi @ercadev, thanks for the idea. The original idea behind this library was to be a Flutter version of https://github.com/twitter-archive/twitter-kit-android, but I agree that the UI should look more modern. If you want, please make a `TweetEmbedded()` and I will merge it and add you to the contributor's list. 

You can also create modern versions for all the Tweets that we have in this library, **that would be awesome** - but please at least for now don't remove the old versions. We should annotate them as `deprecated` for a while, before removing ;-)

**Comment by ercadev** [comment]
I totally see your idea with a copy to the twitter-kit-android. I will create a PR with a `TweetEmbedded()` so that the people who want to have a highly customizable widget can the "old" ones. I was thinking about to keep the `Th`

**Comment by kawa89** [comment]
Version 2.0.0 is out ;) 🎉 
Thanks for the help ;)
