### ISSUE TITLE
How can I get the JSON object of any tweet?

### ISSUE THREAD

**Issue by shanu12joshi** [schibsted/tweet_ui#37]
Hey, a quick question, How can I get the JSON object of any tweet?
I know this is quite a basic question but can't find :(

**Comment by kawa89** [comment]
Hi. You can use this package https://pub.dev/packages/twitter_api to make a Twitter API call. Hope it helps!

**Comment by gadgetreviews** [comment]
> Hi. You can use this package https://pub.dev/packages/twitter_api to make a Twitter API call. Hope it helps!

twitter_api package is too old, not updated for last 2 years and not null safety compliant. Is there any newer and null safety compliant version of this package? 

Thanks

**Comment by wszeborowskimateusz** [comment]
Hello. I am not so sure. But I think you can always call twitter API directly using dart http client.
