### ISSUE TITLE
Showing an error of Unable to load asset : {JSON OBject}

### ISSUE THREAD

**Issue by shanu12joshi** [schibsted/tweet_ui#38]
How can I resolve it? I'm fetching the API data online and trying to show the Tweet.
The endpoint I'm trying to reach: "statuses/show.json
I want to display any tweet by its id without saving the JSON object in assets Folder. 
![WhatsApp Image 2020-07-10 at 1 09 56 AM](https://user-images.githubusercontent.com/42548654/87083353-1aba3200-c24a-11ea-8485-822b17e27ba0.jpeg)

**Comment by kawa89** [comment]
Hi, just create the Tweet widget with our library by passing the JSON response from the API. You don't need to save it to a file.

```dart
TweetView.fromTweet(
    Tweet.fromRawJson(
       res.body // the JSON from Twitter API
);
```

**Comment by shanu12joshi** [comment]
Ya got it, Thanks :)
I am having one more problem
The tweet I'm using to get the data is not showing the images and also not the entire text (Tweet)
TWEET URL: https://twitter.com/tehseenp/status/1281493907436498946 
![WhatsApp Image 2020-07-10 at 5 48 07 PM (1)](https://user-images.githubusercontent.com/42548654/87153786-a62cd500-c2d5-11ea-9ed6-ab1e4701a951.jpeg)
 here:

**Comment by kawa89** [comment]
Try to set the `tweet_mode` to `extended`.
```dart
Future twitterRequest = _twitterOauth.getTwitterRequest(
  // Http Method
  "GET", 
  // Endpoint you are trying to reach
  "statuses/user_timeline.json", 
  // The options for the request
  options: {
    "user_id": "19025957",
    "screen_name": "TTCnotices",
    "count": "20",
    "trim_user": "true",
    "tweet_mode": "extended", // Used to prevent truncating tweets
  },
);
```
If this does not help paste the Jason's that you get :-)

**Comment by shanu12joshi** [comment]
It worked :)
Thank you :)
Closing the issue.

**Comment by kawa89** [comment]
Nice ;) If you would like to contribute, you could write a wiki page on how to get your first tweet using the `twitter_api` library :)

**Comment by shanu12joshi** [comment]
I'll do that for sure :)
