### ISSUE TITLE
Why full tweet not showing.

### ISSUE THREAD

**Issue by KartikPatelOfficial** [schibsted/tweet_ui#48]
In App | In Web
------------ | -------------
<img src="https://user-images.githubusercontent.com/25227206/87844620-79cc1680-c8dc-11ea-8fe1-7519fcf153b0.jpg" alt="drawing" width="200"/>|<img src="https://user-images.githubusercontent.com/25227206/87844625-7df83400-c8dc-11ea-84ab-445c6b920e0f.jpg" alt="drawing" width="200"/>

**Comment by mwolffalonso** [comment]
This happens to me but in retweeeted content, any comments?

**Comment by kawa89** [comment]
Hi @mwolffalonso , please create a new issue and provide more details, like tweet ids, screenshots (please also add how it should look properly)
