### ISSUE TITLE
Question regarding actions when clicking text

### ISSUE THREAD

**Issue by mwolffalonso** [schibsted/tweet_ui#51]
Hello, first of all congratulations, its a great plugin.
In my project i need to trigger an action (call a method, like onTap does for cards) other than opening the twitter app or web when the text is clicked. Is there anyway i can tune that behavior using your plugin?
Thanks!
Martin.

**Comment by kawa89** [comment]
You can always create your own tweet view, based on our classes.
I will have a look on September 25th if I can prepare something for you.

**Comment by kawa89** [comment]
Hi. You can do a similar implementation like it was done here (https://github.com/schibsted/tweet_ui/pull/2), when a custom onTapImage callback was added.

**Comment by mwolffalonso** [comment]
Hello @kawa89

I am trying to use onTapImage in an EmbeddedTweetUI, but i am having errors.
Appreciate your comments about how to use the callback, as there is no reference in the documentation.
Sorry that I am not very proficient in dart, git and flutter to solve this myself.

Thanks!
Martin.

**Comment by mwolffalonso** [comment]
Figured it out sorry

onTapImage: _myFunction

void _myFunction(List<String> imageURLs, int someInt, String someString){
  //Do something with those URL's for example
}

By the way @kawa89 this does not work with the videos correct?

I find that BetterPlayer when opened in a new page does not show any "done" or "exit" button in iOS at least, so i want to customize it.

I cannot use it embedded in TweetView because of an AudioFocus issue i still cannot work out. It seems like BetterPlayer is colliding with the ongoing textToSpeech being read.

Thanks,
Martin.
