### ISSUE TITLE
TweetVM does not take `favorited` from `Tweet`

### ISSUE THREAD

**Issue by elcolie** [schibsted/tweet_ui#52]
**Describe the bug**
TweetVM does not take `favorited` from `tweet`

**To Reproduce**
Use this version
```
tweet_ui: ^2.2.0+3
```

**Expected behavior**
TweetVM be able to hold `favorited` in `bool` datatype. Then `EmbeddedTweetView` can be change the `Icons.favorite_border` to `Icons.favorite`

**Screenshots**
![image](https://user-images.githubusercontent.com/18206728/93249004-d9e71800-f7ba-11ea-8c25-151e6fa6a26e.png)

**Smartphone (please complete the following information):**
 - Device: Android Emulator
 - OS: Android 10
 - Version: API 30

**Comment by kawa89** [comment]
Hi, I will have a look at this on 25th September. If you would like, you can always prepare a Pull Request with the fix.

**Comment by kawa89** [comment]
Fixed in https://github.com/schibsted/tweet_ui/pull/53
Will be available in next release.
