### ISSUE TITLE
video not work in iOS

### ISSUE THREAD

**Issue by ajatsoft** [schibsted/tweet_ui#56]
in example code and in other projects video not  works in iOS 

**Smartphone:**
 - Device: [e.g. iPhone11]
 - OS: [e.g. iOS14]

**Comment by kawa89** [comment]
Hi, this is going to be hard to solve for me, because I don't have an iPhone device and the video player does not work on iPhone simulators.
Can you try to fix it and contribute to this project @ajatsoft ?

**Comment by kawa89** [comment]
👋  I've used another library for video in version `2.4.0`. Can you @ajatsoft check, if it works on iOS now? Thanks!

**Comment by kawa89** [comment]
Finally got an iPhone device for testing. From version `2.4.0` the videos work on iOS.
