### ISSUE TITLE
Support for twitter payload V2.

### ISSUE THREAD

**Issue by YashSavsani** [schibsted/tweet_ui#83]
Please could you provide support for the Twitter payload V2

**Comment by wszeborowskimateusz** [comment]
@YashSavsani I am happy to announce that Twitter API V2 will be supported in the newest version of the package. We are planning to release a new version by the end of this week. It will be a prerelease with Twitter API V2 support.

**Comment by YashSavsani** [comment]
I would like to know will the version support more than four "photos"?

**Comment by wszeborowskimateusz** [comment]
Unfortunately not. You could however file a new issue for adding more than 4 photos support.

**Comment by YashSavsani** [comment]
What type of content type will this version support if you could provide a list of it?

**Comment by wszeborowskimateusz** [comment]
Do you mean media type content? It will support the same as it was for now, except video (as Twitter API V2 doesn't support fetching video URL). 

You can see the whole code in the newest version of dev branch.

**Comment by YashSavsani** [comment]
Yes.

**Comment by YashSavsani** [comment]
Thanks, @wszeborowskimateusz, I appreciate your support. Looking forward to the next update.

**Comment by wszeborowskimateusz** [comment]
@YashSavsani the version is published

**Comment by wszeborowskimateusz** [comment]
https://pub.dev/packages/tweet_ui/versions/4.0.0-dev.0
