### ISSUE TITLE
Can't display a single tweet

### ISSUE THREAD

**Issue by jpcodr** [schibsted/tweet_ui#89]
I'm trying to display a tweet obtained with [Tweets Lookup](https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/api-reference/get-tweets-id#Optional)

```dart
 EmbeddedTweetView.fromTweetV2(
   TweetV2Response.fromRawJson(jsonEncode(tweet)),
 ),
```

but an error is thrown:
`type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<dynamic>' in type cast`

The error it's clear, but how to display correctly a tweet obtained from that endpoint? The data field of tweet response isn't a List

**Comment by mateusz-wszeborowski** [comment]
Could you share with us  an examplar tweet dto that causes such error? @jpcodr

**Comment by jpcodr** [comment]
Hi @mateusz-wszeborowski thanks for the response.

I'm using a simply `Map<String, dynamic>` (encoded with `jsonEncoder`). This is an example of the tweet response I'm getting from Twitter API:

```dart
final tweet = {
          "data": {
            "public_metrics": {
              "retweet_count": 60,
              "reply_count": 1,
              "like_count": 1127,
              "quote_count": 2
            },
            "text": "💚 https://t.co/aQzfPXXblD",
            "attachments": {
              "media_keys": [
                "3_1502580661231792138",
                "3_1502580676830404615",
                "3_1502580690411479041"
              ]
            },
            "created_at": "2022-03-12T09:42:08.000Z",
            "author_id": "1016076290",
            "id": "1502580693011996674"
          },
          "includes": {
            "media": [
              {
                "url": "https://pbs.twimg.com/media/FNo9Jn8XsAoIwFn.jpg",
                "width": 2048,
                "media_key": "3_1502580661231792138",
                "height": 2048,
                "type": "photo"
              },
              {
                "url": "https://pbs.twimg.com/media/FNo9KiDXoAc1lRx.jpg",
                "width": 2048,
                "media_key": "3_1502580676830404615",
                "height": 1363,
                "type": "photo"
              },
              {
                "url": "https://pbs.twimg.com/media/FNo9LUpWYAELulQ.jpg",
                "width": 2048,
                "media_key": "3_1502580690411479041",
                "height": 1366,
                "type": "photo"
              }
            ],
            "users": [
              {
                "id": "1016076290",
                "name": "Sebastian Vettel #5",
                "username": "sebvettelnews"
              }
            ]
          }
        }
```

**Comment by wszeborowskimateusz** [comment]
Hmm, this is strange. I would expect a list in `data` field as it is shown in tweet examples - https://developer.twitter.com/en/docs/twitter-api/data-dictionary/example-payloads

![Screenshot 2022-03-15 at 08 38 30](https://user-images.githubusercontent.com/31158740/158329155-22354315-cde3-4591-a188-1faffda1dc84.png)

**Comment by jpcodr** [comment]
Hi @wszeborowskimateusz 

Yeah i know, but when I retrieve a single tweet by id using this [endpoint](https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/api-reference/get-tweets-id) the response has an object instead a list.

**Comment by wszeborowskimateusz** [comment]
I see, I will try to prepare a version of the library that can handle such a case.

**Comment by jpcodr** [comment]
That's great!

Thank you!

**Comment by wszeborowskimateusz** [comment]
Hello - just uploaded version [4.0.0-dev.1] - please check if you still have a problem there.

@jpcodr
