### ISSUE TITLE
Tweet with video doesn't show the video

### ISSUE THREAD

**Issue by jpcodr** [schibsted/tweet_ui#95]
**Describe the bug**
Hi

I'm using `tweet_video.json`  from the example folder. The tweet renders fine but the video is not displayed even with a clean project. This occurs with both versions `3.0.1` and `4.0.0-dev-1` but the behavior is a little different.
`3.0.1` After load video, `CircularProgressIndicator` is removed you can press play and other actions, the video is playing but the screen remains in black. 

`4.0.0-dev.1` Same as `3.0.1` but the `CircularProgressIndicator` is not removed.

**To Reproduce**
1. Create a new project
2. Install `tweet_ui`
3. Use a tweet with video

**Expected behavior**
The video is displayed correctly

**Screenshots**
![Simulator Screen Shot - iPhone 13 - 2022-04-01 at 15 41 50](https://user-images.githubusercontent.com/3935083/161345236-13b049d1-47d9-4ec3-9084-c6564a74aa7e.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 13 iOS 15.2 (Simulator)
 - OS: MacOs 
 - Version: 12.3.1

**Comment by wszeborowskimateusz** [comment]
Have you tried on real ios device @jpcodr? As written in the Readme 
> Video/GIF Tweets don't work on iOS simulators ([video_player ios instructions](https://pub.dev/packages/video_player#ios))

**Comment by jpcodr** [comment]
HI @wszeborowskimateusz 

> Have you tried on real ios device @jpcodr? As written in the Readme

Where is it written?


> Also did you follow the instructions for ios support for better_player - https://jhomlala.github.io/betterplayer/#/install

Yes

**Comment by wszeborowskimateusz** [comment]
OK, as I see it is written in the README of example folder. Maybe this should be written in the main README? WDYT @kawa89 ?

**Comment by kawa89** [comment]
@wszeborowskimateusz I Think it should be in the main readme :)

**Comment by wszeborowskimateusz** [comment]
OK, I added this comment in this PR - https://github.com/schibsted/tweet_ui/pull/84

**Comment by jpcodr** [comment]
@wszeborowskimateusz 

I confirm that it works on emulator and android device as well as on iOS device. That notice should definitely be on main Readme.

Also it's a bit weird that the videos are not displayed in the simulator. I'm using the video_player plugin to display other videos in my app and works well in the simulator

**Comment by jpcodr** [comment]
@kawa89 @wszeborowskimateusz 

I think this issue can be closed.

Also, i have a question. I don't know where to do it cause is not an issue. Is there any way to autoplay the videos?

**Comment by wszeborowskimateusz** [comment]
As I see there is no such option currently. You can file a feature request so we can add it.

**Comment by jpcodr** [comment]
Thank you @wszeborowskimateusz.

I created the feature request #105
