### ISSUE TITLE
Add the option to show the 'reply_count' on a tweet widget.

### ISSUE THREAD

**Issue by robertmrobo** [schibsted/tweet_ui#99]
Next to the likes/favourites count, I would like to show also how many replies does a tweet have. 

I added the functionality on my local fork and it is ready for submission as a PR if this feature can be a welcomed addition.

The option to show the replies count is optional.

**Comment by wszeborowskimateusz** [comment]
Thanks for your contribution @robertmrobo . If you want us to add this to our plugin, please issue a pull request with your changes so that we can review it and merge it.
